export const urlLocation = `/portal-service`;

var origin = location.origin; //https://172.21.2.116:43509
export const urlLocation2 = `${origin}${urlLocation}`;
const prefixPath = `${origin}${urlLocation}/pms`;
export const PrPath = `${urlLocation}/list-purchase-request`;
export const PoPath = `${urlLocation}/list-purchase-order`;

const path = {
  item: {
    GET_STATUS_SERVICE: `${prefixPath}/items/get-status-service`,
    GET_ALL_ITEM: `${prefixPath}/items/get-list-item`,
    UPDATE_ITEM: `${prefixPath}/items/update-item`,
    CREATE_ITEM: `${prefixPath}/items/new-item`,
    DELETE_ITEM: `${prefixPath}/items/delete-item`,
    GET_BY_NAME: `${prefixPath}/items/get-by-name?name=`,
    GET_ITEM_BY_ID: `${prefixPath}/items/get-item-by-item-id?itemId=`,
    GET_ALL_PRODUCT_TYPE: `${prefixPath}/items/get-list-product-type`,
    GET_ALL_SUB_TYPE: `${prefixPath}/items/get-list-sub-type`
  },
  shipping: {
    GET_ALL: `${prefixPath}/shippings/get-all-shipping`,
    ADD_SHIPPING: `${prefixPath}/shippings/add-shipping`,
    EDIT_SHIPPING: `${prefixPath}/shippings/update-shipping`,
    DEL_SHIPPING: `${prefixPath}/shippings/delete-shipping?shippingAddressId=`,
    GET_BY_NAME: `${prefixPath}/shippings/get-by-name?name=`,
    GET_ALL_SHIPPING_PAGING: `${prefixPath}/shippings/get-all-shipping-paging?page=`,
    GET_ALL_SHIPPING_PAGING_FILTER: `${prefixPath}/shippings/get-all-shipping-paging-filter?type=`,
    GET_LIST_COUNTRY: `${prefixPath}/shippings/get-list-country`
  },
  vendor: {
    UPDATE_VENDOR: `${prefixPath}/vendor/update-vendor`,
    ADD_VENDOR: `${prefixPath}/vendor/add-vendor`,
    DELETE_VENDOR: `${prefixPath}/vendor/delete-vendor?vendorId=`,
    GET_ALL_VENDOR_PAGING_FILTER: `${prefixPath}/vendor/get-all-vendor-paging-filter?page=`,
    GET_DOCUMENT: `${prefixPath}/dowload/`,
  },
  account: {
    GET_ALL_ACCOUNTS: `${prefixPath}/accounts/get-list-user-name`,
    GET_DETAIL_ACCOUNT: `${prefixPath}/accounts/get-detail-account?userName=`,
    GET_PURCHASE_DELEGATE: `${prefixPath}/accounts/get-purchase-delegate?userName=`,
    INSERT_ACCOUNT: `${prefixPath}/accounts/insert-account`,
    UPDATE_ACCOUNT: `${prefixPath}/accounts/update-account`,
    DELETE_ACCOUNT: `${prefixPath}/accounts/delete-account?userId=`,
    GET_DETAIL: `${prefixPath}/accounts/detail-account`,
    GET_ACCOUNT_BY_ID: `${prefixPath}/accounts/get-account-by-id`,
    UPDATE_ACCOUNT_PROFILE: `${prefixPath}/accounts/update-account-profile`,
    GET_ALL_ACCOUNTS_PAGING_FILTER: `${prefixPath}/accounts/get-all-account?page=`,
    GET_ALL_ACCOUNT_INIT_DATA: `${prefixPath}/accounts/get-data-new-account`,
    INSERT_OR_UPDATE_USER_SETTING: `${prefixPath}/accounts/insert-or-update-user-setting`,
    RESET_USER_SETTING_TO_DEFAULT: `${prefixPath}/accounts/reset-user-setting-to-default`,
    GET_ALL_LIST_USER_LDAP: `${prefixPath}/ldap/get-list-user-ldap`,
    GET_LIST_USER_LDAP: `${prefixPath}/ldap/get-user-ldap`,
    UPDATE_DELEGATE_USER: `${prefixPath}/accounts/update-delegate-user`,
    AVATAR: `${urlLocation2}/img/user-profile.jpg`,
    GET_USER_SETTING: `${prefixPath}/accounts/get-user-setting`,
    GET_PROFILE_LIST: `${prefixPath}/accounts/get-profile-list?profileId=`
  },
  permission: {
    GET_ALL_PERMISSIONS: `${prefixPath}/permissions/get-all-permission`,
    GET_PERMISSIONS_BY_LOGIN_USER: `${prefixPath}/permissions/get-permissions-by-login-user`,
    INSERT_PERMISSION: `${prefixPath}/permissions/insert-permission`,
    UPDATE_PERMISSION: `${prefixPath}/permissions/update-permission`,
    DELETE_PERMISSION: `${prefixPath}/permissions/delete-permission`,
    GET_PERMISSIONS_BY_ROLE_ID: `${prefixPath}/permissions/get-permission-by-roleId?roleId=`
  },
  system_config: {
    GET_LIST_SYSTEM_COMFIG: `${prefixPath}/system-config/get-list-system-config`,
    UPDATE_SYSTEM_CONFIG: `${prefixPath}/system-config/update-system-config`
  },
  role: {
    GET_ALL_ROLES: `${prefixPath}/roles/get-all-role`,
    INSERT_ROLE: `${prefixPath}/roles/insert-role`,
    UPDATE_ROLE: `${prefixPath}/roles/update-role`,
    DELETE_ROLE: `${prefixPath}/roles/delete-role`,
    GET_ROLES_BY_LOGIN_USER: `${prefixPath}/roles/get-role-user-login`,
    GET_PERMISSIONS_BY_ROLE: `${prefixPath}/roles/permissions/get-permissions-by-role?roleId=`,
    INSERT_ROLE_PERMISSION: `${prefixPath}/roles/permissions/insert-role-permission`,
    UPDATE_ROLE_PERMISSION: `${prefixPath}/roles/permissions/update-role-permission`,
    DELETE_ROLE_PERMISSION: `${prefixPath}/roles/permissions/delete-role-permission`
  },
  billing: {
    GET_ALL_BILL: `${prefixPath}/billings/get-all-billing`,
    INSERT_BILL: `${prefixPath}/billings/insert-billing`,
    UPDATE_BILL: `${prefixPath}/billings/update-billing`,
    DELETE_BILL: `${prefixPath}/billings/delete-billing`
  },
  general_ledger: {
    GET_ALL_GL: `${prefixPath}/gl/get-list-gl`,
    GET_GL_INFO: `${prefixPath}/gl/get-gl-info`,
    INSERT_GL: `${prefixPath}/gl/insert-gl`,
    UPDATE_GL: `${prefixPath}/gl/update-gl`,
    DELETE_GL: `${prefixPath}/gl/delete-gl`,
    GET_BY_GL_NAME: `${prefixPath}/gl/get-by-gl-name?glName=`,
    GET_LIST_GL_BY_GLCODE: `${prefixPath}/gl/get-list-gl-by-glCode?page=`,
    GET_GL_CODE: `${prefixPath}/gl/get-list-gl-id-gl-code`,
    GET_DETAIL_GL_BY_ID: `${prefixPath}/gl/get-gl-by-id?glId=`,
    GET_GL_YEAR: `${prefixPath}/gl/get-gl-year-for-filter`,
    GET_DATA_FILTER_GL_BALANCE_TRANSACTION: `${prefixPath}/gl/get-all-filter-data-for-gl-balance-listing`,
    GET_LIST_GL_BALANCE_TRANSACTION: `${prefixPath}/gl/get-list-gl-balance-transaction?page=`,
    GET_GL_ID_FOR_ADJUSTMENT: `${prefixPath}/gl/get-list-gl-id-for-adjustment`,
    ADD_GL_ADJUSTMENT: `${prefixPath}/gl/add-gl-adjustment`,
    GET_LIST_ADJUSTMENT: `${prefixPath}/gl/get-list-adjustment`
  },
  email: {
    GET_EMAIL_BY_ID: `${prefixPath}/email/get-email-by-id?email_template_id=`,
    GET_ALL: `${prefixPath}/email/get-list-email`,
    UPDATE_EMAIL: `${prefixPath}/email/update-email`,
    ADD_EMAIL: `${prefixPath}/email/add-email`,
    DELETE_EMAIL: `${prefixPath}/email/delete-email`,
    GET_VARIABLE: `${prefixPath}/email/get-list-variable`,
    SEND_EMAIL: `${prefixPath}/email/send-email`,
    SYSTEM_SEND_MAIL: `${prefixPath}/email/system-send-mail?emailId=`,
    LIST_EMAIL_PAGE: `${urlLocation}/admin-settings/emails/list-email`,
    GET_INIT_DATA_FOR_EMAIL: `${prefixPath}/email/get-initial-data-email?emailId=`,
    REVIEW_EMAIL: `${prefixPath}/email/review-email`
  },
  product_type: {
    GET_ALL_PRODUCT_TYPE: `${prefixPath}/product-types/get-all-product-type?page=`,
    GET_ALL_PRODUCT_TYPE_TO_INSERT_SUB_TYPE: `${prefixPath}/product-types/get-all-product-type-to-insert-sub-type`,
    INSERT_PRODUCT_TYPE: `${prefixPath}/product-types/insert-product-type`,
    INSERTSUB_TYPE_FOR_OLD_PRODUCT_TYPE: `${prefixPath}/product-types/insert-sub-type-for-old-product-type`,
    UPDATE_PRODUCT_TYPE: `${prefixPath}/product-types/update-product-type`,
    DELETE_PRODUCT_TYPE: `${prefixPath}/product-types/delete-product-type`
  },
  cost_center: {
    GET_CC_WITH_FILTER: `${prefixPath}/cc/get-list-cc-with-filter`,
    INSERT_CC: `${prefixPath}/cc/insert-cc`,
    UPDATE_CC: `${prefixPath}/cc/update-cc`,
    DELETE_CC: `${prefixPath}/cc/delete-cc?ccId=`,
    GET_LIST_ACTIVE_BUDGET_OWNER: `${prefixPath}/cc/get-list-active-budget-owner-account`
  },
  ldap_settings: {
    GET_ALL_PROVIDER: `${prefixPath}/ldap-settings/get-all-provider`,
    ADD_OR_UPDATE_PROVIDER: `${prefixPath}/ldap-settings/add-or-update-provider`,
    DELETE_PROVIDER: `${prefixPath}/ldap-settings/delete-provider`,
    CHECK_NETWORK_PARAMETER: `${prefixPath}/ldap/check-network-parameter`,
    CHECK_AUTHENTICATION: `${prefixPath}/ldap/check-authentication`
  },
  purchase_request: {
    GET_ALL_PR_FILLTER: `${prefixPath}/purchase-request/get-list-purchase-request-filter?`,
    GET_ALL_PR: `${prefixPath}/purchase-request/get-list-purchase`,
    GET_PR_SUBMITTED: `${prefixPath}/purchase-request/get-list-purchase-submitted`,
    GET_LIST_PR_VOID: `${prefixPath}/purchase-request/get-list-purchase-void`,
    GET_LIST_PR_IN_PROGRESS: `${prefixPath}/purchase-request/get-list-purchase-in-progress`,
    UPLOAD_FILE: `${prefixPath}/purchase-request/upload`,
    DOWLOAD_FILE: `${prefixPath}/purchase-request/download?document_id=`,
    GET_LIST_REVIEW_PR: `${prefixPath}/purchase-request/get-list-purchase-review`,
    APPROVE_PR: `${prefixPath}/purchase-request/approve-purchase-request?prId=`,
    REJECT_PR: `${prefixPath}/purchase-request/reject-purchase-request`,
    VOID_PR: `${prefixPath}/purchase-request/void-purchase-request?prId=`,
    UNVOID_PR: `${prefixPath}/purchase-request/unvoid-purchase-request?prId=`,
    GET_PR_BY_CODE: `${prefixPath}/purchase-request/get-purchase-by-code?purchaseCode=`,
    GET_PR_APPROVE_BY_ID: `${prefixPath}/purchase-request/get-pr-approve-by-id?purchaseRequestId=`,
    GET_LIST_PR_APPROVER: `${prefixPath}/purchase-request/get-list-purchase-request-approver`,
    GET_LIST_PR_APPROVE: `${prefixPath}/purchase-request/get-list-purchase-request-approve`,
    INSERT_PR: `${prefixPath}/purchase-request/create-purchase-request`,
    UPDATE_PR: `${prefixPath}/purchase-request/update-purchase-request`,
    GET_PR_DETAILS_BY_PR_ID: `${prefixPath}/purchase-request/get-purchase-details-by-pr-id?pr_id=`,
    GET_ALL_PR_INIT_DATA: `${prefixPath}/purchase-request/get-init-data-for-create?purchaseCode=`,
    GET_DATA_FOR_ROUTING_TAB: `${prefixPath}/purchase-request/get-data-for-approval-tab?prCode=`,
    CHECK_EDITING: `${prefixPath}/purchase-request/check-editing?prCode=`,
    DELETE_EDITING: `${prefixPath}/purchase-request/delete-editing?prCode=`,
    DUPLICATE: `${prefixPath}/purchase-request/duplicate?prId=`,
    SUBMIT_PR_FOR_APPROVAL: `${prefixPath}/purchase-request/submit-pr-for-approval`,
    GET_LIST_ITEMS_BY_PR_CODE: `${prefixPath}/purchase-request/get-list-item-by-pr-code?purchaseCode=`,
    EXPORT_DETAILS: `${prefixPath}/purchase-request/export-details?prId=`,
    EXPORT_ITEM: `${prefixPath}/purchase-request/export-item?prId=`,
    GET_TRANSACTION_PR: `${prefixPath}/purchase-request/get-pr-transaction-history?purchaseCode=`,
    GET_LIST_GL_BY_CC_ID: `${prefixPath}/purchase-request/get-gl-by-cc-id?costCenter=`,
    GET_LAST_STATUS_PR_BY_ID: `${prefixPath}/purchase-request/get-last-status-pr-by-code?purchaseCode=`,
    CHANGE_STATUS_PR_BY_ID: `${prefixPath}/purchase-request/change-status-pr-by-code`,
    GET_MESSAGE_HISTORY: `${prefixPath}/message/get-message-channels-by-purchase-code?purchaseCode=`,
    INSERT_MESSAGE: `${prefixPath}/message/insert-message-contents-by-purchase-code`,
    GET_ITEM_DETAIL_BY_ITEMCODE: `${prefixPath}/purchase-request/get-item-detail-by-item-name?itemName=`,
    GET_DATA_LIST_ITEM: `${prefixPath}/purchase-request/get-list-data-item`,
    UNVOID_PR_BY_CODE: `${prefixPath}/purchase-request/unvoid-pr-by-code`,
    GET_PERMISSION_DELEGATE: `${prefixPath}/purchase-request/get-str-permission-delegate-permission?purchaseCode=`,
    DATA_HEADER: `${prefixPath}/purchase-request/get-init-header-pr?purchaseCode=`,
    GET_MESSAGE_CONTENT: `${prefixPath}/message/get-message-content-by-message-id?messageId=`,
    GET_ROLE_BY_PURCHASE_CODE: `${prefixPath}/purchase-request/get-role-by-purchase-code?purchaseCode=`,
    GET_ROLE_BY_ROUTING: `${prefixPath}/purchase-request/get-role-by-routing?purchaseCode=`,
    INSERT_ROLE_ROUTING: `${prefixPath}/purchase-request/insert-role-by-routing`,
    SUBMIT_PR_FOR_APPROVAL_ROUTING: `${prefixPath}/purchase-request/submit-pr-for-approval-routing`,
    INSERT_CHANNEL: `${prefixPath}/message/insert-message-channel-for-pr`,
    UPDATE_CHANNEL: `${prefixPath}/message/update-message-channel`,
    INSERT_CONTENT: `${prefixPath}/message/insert-message-content-for-pr`,
    GET_ROLE_ADDITIONAL_PURCHASE_CODE: `${prefixPath}/purchase-request/get-role-additional-by-purchase-code?purchaseCode=`,
    DELETE_ROLE_ADDITIONAL: `${prefixPath}/purchase-request/delete-role-additional?id=`,
    RESUBMITTED_PR_BY_CODE: `${prefixPath}/purchase-request/resubmitted-pr-by-code`,
    GET_LIST_MESSAGE_HISTORY_PR: `${prefixPath}/purchase-request/get-list-message-history-pr`,
    GET_USER_HAVE_ACCESS_TO_CHANNEL: `${prefixPath}/purchase-request/get-list-user-have-access-to-channel?purchaseCode=`,
    GET_BUTTON_EDIT_PR: `${prefixPath}/purchase-request/get-button-edit-pr?purchaseCode=`,
    GET_LAST_STATUS_PENDING_APPROVAL_PR: `${prefixPath}/purchase-request/get-last-status-pending-approval-pr?purchaseCode=`,
    GET_ROUTING_POLICY_BY_DEPARTMENT_OF_CREATER: `${prefixPath}/purchase-request/get-routing-policy-by-department-of-creater?purchaseCode=`,
    GET_LIST_ITEM_FOR_CONVERT_TO_PO: `${prefixPath}/purchase-request/get-list-item-for-convert-to-po-by-prCode?purchaseCode=`,
    GET_BUTTON_EDIT_PO: `${prefixPath}/purchase-request/get-button-edit-po?purchaseCode=`,
    GET_AUTO_COMPLETE_PREFFERED_VENDOR: `${prefixPath}/purchase-request/get-auto-complete-preferred-vendor`,
    GET_LIST_RECEIVER: `${prefixPath}/message/get-list-receiver`,
    SUBMIT_PR: `${prefixPath}/purchase-request/submit-pr`,
    GET_MESSAGE_DETAIL_BY_ID: `${prefixPath}/message/get-message-detail-by-id?messageId=`,
    CHECK_INACTIVE: `${prefixPath}/purchase-request/check-inactive-data`,
    CHECK_AVAILABLE_BALANCE_NEGATIVE: `${prefixPath}/purchase-request/check-available-balance-negative-pr?purchaseCode=`,
    CHECK_VERIFY_STATUS_PURCHASE: `${prefixPath}/purchase-request/verify-status-purchase?`
  },
  invoice: {
    GET_ALL_INVOICE: `${prefixPath}/invoices/get-all-invoice`,
    INSERT_INVOICE: `${prefixPath}/invoices/insert-invoice`,
    UPDATE_INVOICE: `${prefixPath}/invoices/update-invoice`,
    DELETE_INVOICE: `${prefixPath}/invoices/delete-invoice`
  },
  notification: {
    GET_LIST_NOTIFICATION_BY_STATUS: `${prefixPath}/notifications/get-list-notification-by-status?notificationStatus=`,
    GET_ALL_LIST_NOTIFICATION: `${prefixPath}/notifications/get-all-list-notification`,
    GET_DETAIL_NOTIFICATION: `${prefixPath}/notifications/get-detail-notification?prId=`,
    UPDATE_NOTIFICATION_STATUS: `${prefixPath}/notifications/update-notification-status`,
    UPDATE_NOTIFICATION_TYPE: `${prefixPath}/notifications/update-notification-type`,
    INSERT_NOTIFICATION: `${prefixPath}/notifications/insert-notification`,
    SEND_NOTIFICATION_ALL: `${prefixPath}/notifications/send-messenger-all`,
    SEND_NOTIFICATION_ONE: `${prefixPath}/notifications/send-messenger-one`,
    GET_NOTIFICATION_BY_ID: `${prefixPath}/notifications/get-notification-by-id?notifiId=`
  },
  purchase_order: {
    CHANGE_STATUS_PO_BY_ID: `${prefixPath}/purchase-order/change-status-po-by-code`,
    GET_LAST_STATUS_PENDING_APPROVAL_PO: `${prefixPath}/purchase-order/get-last-status-pending-approval-po?purchaseCode=`,
    GET_LAST_STATUS_PO_BY_ID: `${prefixPath}/purchase-order/get-last-status-po-by-code?purchaseCode=`,
    GET_ALL_PURCHASE_ORDER: `${prefixPath}/purchase-order/get-list-purchase-order?`,
    GET_PO_BY_CODE: `${prefixPath}/purchase-order/get-purchase-order-by-code?poCode=`,
    GET_LIST_ITEM_BY_PO_CODE: `${prefixPath}/purchase-order/get-item-by-purchase-order-code?poCode=`,
    GET_GENERAL_DATA: `${prefixPath}/purchase-order/get-general-data`,
    UPDATE_PO: `${prefixPath}/purchase-order/update-purchase-order`,
    DELETE_PO: `${prefixPath}/purchase-order/delete-purchase-order?poCode=`,
    INSERT_PO: `${prefixPath}/purchase-request/convert-pr-to-po`,
    CONVERT_PO_TO_PO_APPROVALS: `${prefixPath}/purchase-order/convert-po-to-po-approvals`,
    GET_ITEM_RECEIPT: `${prefixPath}/purchase-order/get-item-receipt?poCode=`,
    GET_ITEM_RECEIPT_DETAIL: `${prefixPath}/purchase-order/get-item-receipt-detail?receiveId=`,
    INSERT_ITEM_RECEIPT: `${prefixPath}/purchase-order/insert-item-receipt`,
    UPDATE_ITEM_RECEIPT: `${prefixPath}/purchase-order/update-item-receipt`,
    REMOVE_ITEM_RECEIPT: `${prefixPath}/purchase-order/remove-item-receipt`,
    UPLOAD_INVOICE: `${prefixPath}/purchase-order/upload-invoice`,
    REMOVE_INVOICE: `${prefixPath}/purchase-order/remove-invoice`,
    INSERT_PAYMENT: `${prefixPath}/purchase-order/insert-register-payment`,
    UPDATE_PAYMENT: `${prefixPath}/purchase-order/update-register-payment`,
    REMOVE_PAYMENT: `${prefixPath}/purchase-order/remove-register-payment`,
    GET_LIST_GL: `${prefixPath}/purchase-order/get-list-gl?poCode=`,
    GET_LIST_ITEM: `${prefixPath}/purchase-order/get-list-item?poCode=`,
    GET_LIST_CREDIT_NOTE: `${prefixPath}/purchase-order/get-list-purchase-order-credit-note?poCode=`,
    GET_LAST_STATUS_PO_BY_ID: `${prefixPath}/purchase-order/get-last-status-po-by-code?purchaseCode=`,
    INSERT_OR_UPDATE_CREDIT_NOTE: `${prefixPath}/purchase-order/insert-or-update-credit-note?poCode=`,
    DELETE_CREDIT_NOTE: `${prefixPath}/purchase-order/delete-credit-note`,
    GET_TRANSACTION_PO: `${prefixPath}/purchase-order/get-po-transaction-history?purchaseCode=`,
    UNVOID_UNREJECT_PO_BY_CODE: `${prefixPath}/purchase-order/unvoid-unreject-po-by-code`,
    GET_INIT_HEADER_PO: `${prefixPath}/purchase-order/get-init-header-po?purchaseCode=`,
    GET_ASSOCIATE_ROLE_FOR_PO: `${prefixPath}/purchase-order/get-roles-for-po?purchaseCode=`,
    GET_DATA_FOR_ROUTING_TAB: `${prefixPath}/purchase-order/get-data-for-routing-tab?poCode=`,
    GET_ROLE_BY_PURCHASE_CODE: `${prefixPath}/purchase-order/get-role-by-purchase-code?purchaseCode=`,
    GET_ROLE_ADDITIONAL_PURCHASE_CODE: `${prefixPath}/purchase-order/get-role-additional-by-purchase-code?purchaseCode=`,
    GET_ROLE_BY_ROUTING: `${prefixPath}/purchase-order/get-role-by-routing?purchaseCode=`,
    INSERT_ROLE_ROUTING: `${prefixPath}/purchase-order/insert-role-by-routing`,
    SUBMIT_PO_FOR_APPROVAL_ROUTING: `${prefixPath}/purchase-order/submit-po-for-approval-routing`,
    DELETE_ROLE_ADDITIONAL: `${prefixPath}/purchase-order/delete-role-additional?id=`,
    GET_LIST_COMMENT_PO: `${prefixPath}/purchase-order/get-list-comment-purchase`,

    GET_BILLING_SHIPPING: `${prefixPath}/purchase-order/get-billing-shipping`,
    GET_LIST_MESSAGE_HISTORY_PO: `${prefixPath}/purchase-order/get-list-message-history-po`,
    DELETE_PO: `${prefixPath}/purchase-order/delete-po`,
    GET_INIT_DATA_NEW_INVOICE: `${prefixPath}/purchase-order/get-data-invoice-by-code?poCode=`,
    INSERT_INVOICE: `${prefixPath}/purchase-order/add-invoice`,
    UPDATE_INVOICE: `${prefixPath}/purchase-order/update-invoice`,
    GET_INVOICE_BY_CODE: `${prefixPath}/purchase-order/get-list-invoice-by-code?poCode=`,
    GET_LIST_ITEM_PO_DETAILS_BY_PO_ID: `${prefixPath}/purchase-order/get-item-by-purchase-order-id?poId=`,
    GET_LIST_PAYMENTY_RECEIPT_BY_PO_CODE: `${prefixPath}/purchase-order/get-list-payment-receipt-by-poCode?poCode=`,
    GET_LIST_PAYMENTY_RECEIPT_DETAIL_BY_PAYMENT_ID: `${prefixPath}/purchase-order/get-list-payment-receipt-detail-by-paymentId?paymentId=`,
    GET_LIST_PAYMENT_METHOD: `${prefixPath}/purchase-order/get-list-payment-method`,
    INSERT_PAYMENT_RECEIPT: `${prefixPath}/purchase-order/insert-payment-receipt`,
    UPDATE_PAYMENT_RECEIPT: `${prefixPath}/purchase-order/update-payment-receipt`,
    DELETE_PAYMENT_RECEIPT: `${prefixPath}/purchase-order/delete-payment-receipt?paymentId=`,
    GET_AUTO_COMPLETE_INVOICE: `${prefixPath}/purchase-order/get-list-auto-complete-invoice?invoiceId=`,
    DELETE_INVOICE: `${prefixPath}/purchase-order/delete-invoice`,
    GET_LIST_REDIT_DETAIL: `${prefixPath}/purchase-order/get-list-purchase-order-credit-note-details?creditNoteId=`,
    GET_LIST_ITEM_FOR_PO_BY_CREDIT_ID: `${prefixPath}/purchase-order/get-list-item-for-po-by-credit-id?poCode=`,
    REMOVE_CREDIT_NOTE: `${prefixPath}/purchase-order/delete-credit-note?creditNoteId=`,
    GET_PAID_AND_PAYABLE_TOTAL_OF_PO: `${prefixPath}/purchase-order/get-paid-and-payable-total-of-po?poCode=`,
    CHECK_CLOSE_INVOICE: `${prefixPath}/purchase-order/get-data-check-close-invoice?poCode=`,
    PRINT_PO: `${urlLocation2}/report?poCode=`,
    GET_CREDIT_INVOICE_BY_PO_CODE: `${prefixPath}/purchase-order/get-list-credit-invoice-by-code?poCode=`,
    GET_CREDIT_INVOICE_AMOUNT_USING: `${prefixPath}/purchase-order/get-list-credit-invoice-amount-using?poCode=`,
    PO_CHECK_AVAILABLE_BALANCE_NEGATIVE: `${prefixPath}/purchase-order/check-available-balance-negative-po`,

  },
  message_center: {
    GET_MESSAGE_CHANNEL: `${prefixPath}/message-center/get-message-channels-by-user-account?purchaseCode=`,
    GET_PERSONAL_MESSAGE_CHANNEL: `${prefixPath}/message-center/get-personal-message-channels-by-user-account?page=`,
    GET_PURCHASE_LIST_FOR_MESSAGE_CENTER: `${prefixPath}/message-center/get-list-purchase-for-message-center`
  },
  project_info: {
    GET_ALL_PROJECT_INFO: `${prefixPath}/project-infos/get-all-project-info`,
    INSERT_PROJECT_INFO: `${prefixPath}/project-infos/insert-project-info`,
    UPDATE_PROJECT_INFO: `${prefixPath}/project-infos/update-project-info`,
    DELETE_PROJECT_INFO: `${prefixPath}/project-infos/delete-project-info`
  },
  department: {
    GET_ALL_DEPARTMENT: `${prefixPath}/department/get-list-department?page=`,
    GET_DEPARTMENT_INFO: `${prefixPath}/department/get-department-info`,
    GET_DEPARTMENT_BY_ID: `${prefixPath}/department/get-department-by-id?departmentID=`,
    INSERT_DEPARTMENT: `${prefixPath}/department/insert-department`,
    UPDATE_DEPARTMENT: `${prefixPath}/department/update-department`,
    DELETE_DEPARTMENT: `${prefixPath}/department/delete-department?deptId=`
  },
  currency: {
    GET_ALL_CURRENCY: `${prefixPath}/currencies/get-all-currency`,
    INSERT_CURRENCY: `${prefixPath}/currencies/insert-currency`,
    UPDATE_CURRENCY: `${prefixPath}/currencies/update-currency`,
    DELETE_CURRENCY: `${prefixPath}/currencies/delete-currency`,
    GET_LIST_CURRENCY_PAGING: `${prefixPath}/currencies/get_currency_paging_filter?page=`
  },
  dashboard: {
    GET_LIST_RECENTLY_PURCHASE: `${prefixPath}/dashboard/get-list-purchase-recently`,
    GET_LIST_PR_LAST_MONTH: `${prefixPath}/dashboard/get-list-purchase-last-month?perMonth=`,
    GET_LIST_PR_DETAILS: `${prefixPath}/dashboard/get-purchase-details`,
    GET_LIST_MESSAGE_HISTORY_PR_PO: `${prefixPath}/dashboard/get-list-message-history-pr-po`,
    GET_TOTAL_STATUS_PURCHASE: `${prefixPath}/dashboard/get-total-status-purchase-by-user-name`
  },
  routing: {
    GET_ALL: `${prefixPath}/routing/get-list-routing-policy`,
    INSERT_ROUTING: `${prefixPath}/routing/insert-routing-policy`,
    UPDATE_ROUTING: `${prefixPath}/routing/update-routing-policy`,
    DELETE_ROUTING: `${prefixPath}/routing/delete-routing?routingId=`,
    GET_DATE_ROUTING_INIT: `${prefixPath}/routing/get-list-init-data-for-create`,
    GET_ROUTING_BY_NAME: `${prefixPath}/routing/get-list-routing-policy-by-routingName?routingName=`,
    GET_ALL_ROUTING_PAGING_FILTER: `${prefixPath}/routing/get-all-routing-paging-filter?page=`
  },
  monetary_classes: {
    GET_ALL_MONETARY: `${prefixPath}/monetary-classes/get-all-monetary-class`,
    INSERT_MONETARY: `${prefixPath}/monetary-classes/insert-or-update-monetary-class`,
    UPDATE_MONETARY: `${prefixPath}/monetary-classes/insert-or-update-monetary-class`,
    DELETE_MONETARY: `${prefixPath}/monetary-classes/delete-monetary-class?classGroup=`,
    GET_LIST_CLASS_GROUP: `${prefixPath}/monetary-classes/get-list-class-group`
  },
  associate_role: {
    GET_ALL_ASSOCIATE_ROLE: `${prefixPath}/roles/get-all-roles`,
    INSERT_ASSOCIATE_ROLE: `${prefixPath}/roles/insert-roles`,
    UPDATE_ASSOCIATE_ROLE: `${prefixPath}/roles/update-roles`,
    DELETE_ASSOCIATE_ROLE: `${prefixPath}/roles/delete-roles`,
    GET_LIST_ASSOCIATE_ROLE_PAGING: `${prefixPath}/roles/get-all-roles-paging-filter?page=`
  },
  report: {
    GET_ALL_REPORT_PAGING_FILTER: `${prefixPath}/report/get-all-report-paging-filter?page=`,
    GET_INIT_DATA_FOR_REPORT: `${prefixPath}/report/get-list-init-data-for-report`
  },
  inventory: {
    GET_ASSET_LISTING_FILTER: `${prefixPath}/asset/get-asset-listing-filter`,
    GET_ALL_FILTER_DATA_FOR_ASSET_LISTING: `${prefixPath}/asset/get-all-filter-data-for-asset-listing`,
    LOCATION_SETTING: {
      GET_INIT_DATA_FOR_ADDING_MODAL: `${prefixPath}/location/get-init-data-for-adding-modal`,
      GET_LIST_LOCATION_OPTION: `${prefixPath}/location/get-list-location-option`,
      COUNTRY: {
        GET_ALL_DATA_COUNTRIES: `${prefixPath}/location/get-country-listing-filter`,
        GET_BUILDING_LISTING_FILTER: `${prefixPath}/location/get-building-listing-filter`,
        INSERT_COUNTRIES: `${prefixPath}/location/add-new-country-data`,
        UPDATE_COUNTRIES: `${prefixPath}/location/update-country-data-by-id`,
        DELETE_COUNTRIES: `${prefixPath}/location/delete-country-data`,
      },
      BUILDING: {
        INSERT_BUILDING: `${prefixPath}/location/add-new-building-data`,
        UPDATE_BUILDING: `${prefixPath}/location/update-building-data-by-id`,
        DELETE_BUILDING: `${prefixPath}/location/delete-building-data`,
        GET_FLOOR_LISTING_FILTER: `${prefixPath}/location/get-list-floor`,

      },
      FLOOR: {
        INSERT_FLOOR: `${prefixPath}/location/add-new-floor-data`,
        UPDATE_FLOOR: `${prefixPath}/location/update-floor-data-by-id`,
        DELETE_FLOOR: `${prefixPath}/location/delete-floor-data`,
      },
      ROOM: {
        GET_ROOMS_LISTING_FILTER: `${prefixPath}/location/get-list-room`,
        INSERT_ROOM: `${prefixPath}/location/add-new-room-data`,
        UPDATE_ROOM: `${prefixPath}/location/update-room-data-by-id`,
        DELETE_ROOM: `${prefixPath}/location/delete-room-data`,
      }

    },
    asset: {
      INSERT_ASSET: `${prefixPath}/asset/add-new-asset-data`,
      UPDATE_ASSET: `${prefixPath}/asset/update-asset-data-by-id`,
      DELETE_ASSET: `${prefixPath}/asset/delete-asset-data`,
      GET_ASSET_BY_ID: `${prefixPath}/asset/get-asset-data-by-id?assetId=`,
      ASSIGN_ASSET: `${prefixPath}/asset/assign-asset-data-by-id`,
      UNASSIGN_ASSET: `${prefixPath}/asset/unassign-asset-data-by-id`,
      DISPOSE_ASSET: `${prefixPath}/asset/dispose-asset-data-by-id`,
      GET_DATA_FOR_ASSET_WHEN_NEW: `${prefixPath}/asset/get-data-for-asset-management`,
      GET_DATA_ASSET_IT_BY_ASSET_ID: `${prefixPath}/asset/get-asset-it-information-by-asset-id`,
      GET_DATA_ASSET_SOFTWARE_BY_ASSET_ID: `${prefixPath}/asset/get-asset-software-by-asset-id`,
      GET_DATA_ASSET_COMPONENT_BY_PARENT_ASSET_ID: `${prefixPath}/asset/get-asset-component-by-parent-asset-id`,
      GET_OPTION_DATA_FOR_ASSET_BY_PARENT_ID: `${prefixPath}/asset/get-asset-option-data-by-parent-id`,
      GET_OPTION_DATA_FOR_ASSIGN_MODAL_BY_ASSET_ID: `${prefixPath}/asset/get-asset-option-data-for-assign-modal-by-asset-id`,
      GET_DATA_FOR_ASSET_WHEN_EDIT: `${prefixPath}/asset/get-asset-option-data-by-asset-id`,
      GET_ASSET_HISTORY_INFO_BY_ASSET_ID: `${prefixPath}/asset/get-asset-history-info-by-asset-id?assetId=`,
      GET_LIST_AUDIT_TRAIL_REPORT: `${prefixPath}/asset/get-audit-trail-report`,
      GET_LIST_COMPONENT_TO_ATTACH: `${prefixPath}/asset/get-list-component-to-attach`,
      DETACH_COMPONENT: `${prefixPath}/asset/detach-component`,
      ATTACH_COMPONENT: `${prefixPath}/asset/attach-component`,
      GET_LICENSES_BY_SOFTWARE: `${prefixPath}/asset/get-licenses-by-software?softwareId=`,
      GET_LIST_ASSET_DISPOSAL_BY_COUNTRY_ID: `${prefixPath}/asset/get-list-asset-pending-disposal?textSeach=`,
      APPROVE_ASSET_DISPOSAL: `${prefixPath}/asset/approve-asset-disposal`,
      GET_RECEIVE_ITEM_DETAIL_ID: `${prefixPath}/asset/get-receive-item-detail-id-in-asset`,
      GET_DATA_FOR_ASSET_PENDING_DISPOSAL: `${prefixPath}/asset/get-all-filter-data-for-asset-pending-disposal`
    },
    ASSET_SETTING: {
      GET_ALL_FILTER_DATA_FOR_ASSET_SETTING: `${prefixPath}/asset/get-all-filter-data-for-asset-setting`,
      GET_LIST_ASSET_TYPE: `${prefixPath}/asset/get-asset-type`,
      GET_LIST_ASSET_SUB_TYPE: `${prefixPath}/asset/get-asset-sub-type`,
      GET_LIST_ASSET_ITEM_TYPE: `${prefixPath}/asset/get-asset-item-type`,
      ADD_ASSET_TYPE: `${prefixPath}/asset/add-asset-type`,
      UPDATE_ASSET_TYPE: `${prefixPath}/asset/update-asset-type`,
      DELETE_ASSET_TYPE: `${prefixPath}/asset/delete-asset-type`,
      ADD_ASSET_SUB_TYPE: `${prefixPath}/asset/add-asset-sub-type`,
      UPDATE_ASSET_SUB_TYPE: `${prefixPath}/asset/update-asset-sub-type`,
      DELETE_ASSET_SUB_TYPE: `${prefixPath}/asset/delete-asset-sub-type`,
      ADD_ASSET_ITEM_TYPE: `${prefixPath}/asset/add-asset-item-type`,
      UPDATE_ASSET_ITEM_TYPE: `${prefixPath}/asset/update-asset-item-type`,
      DELETE_ASSET_ITEM_TYPE: `${prefixPath}/asset/delete-asset-item-type`,
      GET_ALL_FILTER_DATA_FOR_ASSET_SUB_TYPE: `${prefixPath}/asset/get-all-filter-data-for-asset-sub-type`,
      GET_ALL_FILTER_DATA_FOR_ASSET_ITEM_TYPE: `${prefixPath}/asset/get-all-filter-data-for-asset-item-type`,
      GET_ASSET_SUB_TYPE_BY_ASSET_TYPE_ID: `${prefixPath}/asset/get-asset-sub-type-by-asset-type-id`,
      GET_ALL_FILTER_DATA_FOR_ASSET_STATE: `${prefixPath}/asset/get-all-filter-data-for-asset-state`,
      GET_LIST_ASSET_STATE: `${prefixPath}/asset/get-asset-state`,
      ADD_ASSET_STATE: `${prefixPath}/asset/add-asset-state`,
      UPDATE_ASSET_STATE: `${prefixPath}/asset/update-asset-state`,
      DELETE_ASSET_STATE: `${prefixPath}/asset/delete-asset-state`,
      GET_ALL_FILTER_DATA_FOR_SOFTWARE_TYPE: `${prefixPath}/asset/get-all-filter-data-for-software-type`,
      GET_LIST_SOFTWARE_TYPE: `${prefixPath}/asset/get-software-type`,
      ADD_SOFTWARE_TYPE: `${prefixPath}/asset/add-software-type`,
      UPDATE_SOFTWARE_TYPE: `${prefixPath}/asset/update-software-type`,
      DELETE_SOFTWARE_TYPE: `${prefixPath}/asset/delete-software-type`,
      GET_ALL_OPTION_FOR_MANAGE_ASSET_SUB_TYPE: `${prefixPath}/asset/get-all-option-for-manage-asset-sub-type`,
      GET_ALL_OPTION_FOR_MANAGE_ASSET_ITEM_TYPE: `${prefixPath}/asset/get-all-option-for-manage-asset-item-type`
    }
  },
  theme: {
    DEFAULT: `${urlLocation2}/css/style.default.css`,
    BLUE: `${urlLocation2}/css/style.blue.css`,
    GREEN: `${urlLocation2}/css/style.green.css`,
    PINK: `${urlLocation2}/css/style.pink.css`,
    ORANGE: `${urlLocation2}/css/style.orange.css`,
    PURPLE: `${urlLocation2}/css/style.purple.css`
  },
  sidebar_image: {
    NONE: `${urlLocation2}/img/transparent.png`,
    MOUNTAIN: `${urlLocation2}/img/mountain.jpg`,
    RIVER: `${urlLocation2}/img/river.jpg`,
    CITY: `${urlLocation2}/img/city.jpg`,
    FOREST: `${urlLocation2}/img/forest.jpg`,
    "CITY-AT-DAY": `${urlLocation2}/img/city-at-day.jpg`,
    "CITY-AT-NIGHT": `${urlLocation2}/img/city-at-night.jpg`,
    PEACEFUL: `${urlLocation2}/img/peaceful.jpg`,
    FOG: `${urlLocation2}/img/fog.jpg`
  },
  WS: {
    END_POINT: `${urlLocation2}/WebSocketEndPoint`,
    END_POINT_CHECK_MODE: `${urlLocation2}/WebSocketEndPointCheckMode`,
    TOPIC_CHECK_EDITING: "/user/queue/checkModeEditing",
    TOPIC_SEND_MESSAGE_CHECK_EDITING: "/app/checkEditing",
    UNLOCK_PURCHASE: "/app/unLockPurchase",
    TOPIC_CONVERSATION_PR_PO: "/user/queue/conversation/pr-po",
    TOPIC_NOTIFY_TO_ALL: "/queue/sendNotifyToAll",
    TOPIC_NOTIFY_TO_ONE: "/user/queue/sendNotifyToOne",
    TOPIC_CHECK_LOGIN_MULTIPLE_SESSION: "/user/queue/checkLoginMultipleSession",
    CHECK_SESSION: `${urlLocation2}/check-session`,
    TOPIC_SEND_MESSAGE: "/app/chat.sendMessage"
  },
  error_page: {
    500: `${urlLocation2}/erroraaaaaaa`,
    400: `${urlLocation2}/error-400`,
    401: `${urlLocation2}/error-401`
  },
  attachment_doc: {
    INSERT_ATTACHMENTS_DOC: `${prefixPath}/attachments/insert-attachments`,
    DELETE_ATTACHMENTS_DOC: `${prefixPath}/attachments/delete-attachments?purchaseCode=`,
    GET_ATTACHMENT_BY_PURCHASE_CODE: `${prefixPath}/attachments/get-attachments?purchaseCode=`,
    UPLOAD_MULTIPLE_SAME_TIME: `${prefixPath}/attachments/save-all-file-same-time`,
    UPLOAD_MULTIPLE_FILE_ASSET: `${prefixPath}/attachments/insert-attachments-asset`,
    GET_ATTACHMENT_BY_ASSET_ID: `${prefixPath}/attachments/get-attachments-asset?assetId=`,

  },
  contract: {
    GET_DATA_FOR_ADD_CONTRACT: `${prefixPath}/asset/get-data-for-add-contract`,
    GET_LICENSES_TYPE_AND_SOFTWARE: `${prefixPath}/asset/get-licenses-type-and-software`,
    GET_SOFTWARE_BY_ID: `${prefixPath}/asset/get-software-by-id?softwareId=`,
    ADD_CONTRACT: `${prefixPath}/asset/add-contract`,
    GET_LIST_CONTRACT_FILTER: `${prefixPath}/asset/get-list-contract-filter?`,
    GET_DATA_INIT_FILTER_CONTRACT: `${prefixPath}/asset/get-data-init-filter-contract`,
    DELETE_CONTRACT_BY_ID: `${prefixPath}/asset/delete-contract-by-id`,
    GET_CONTRACT_BY_ID: `${prefixPath}/asset/get-contract-by-id?contractId=`,
    GET_CHILD_CONTRACT_BY_PARENT_CONTRACT: `${prefixPath}/asset/get-list-child-contract-by-parent-contract?parentContractId=`,
    GET_CHILD_CONTRACT_BY_AVAILABLE: `${prefixPath}/asset/get-list-child-contract-available?contractId=`,
    GET_LIST_LICENSE_DETAILS_BY_CONTRACT_ID: `${prefixPath}/asset/get-list-license-details?contractId=`,
    CREATED_OR_UPDATED_CONTARCT: `${prefixPath}/asset/created-or-updated-contract`
  },
  user_rights: {
    GET_LIST_PROFILE_FILTER: `${prefixPath}/user-rights/get-list-profile-filter?page=`,
    GET_LIST_MODULE: `${prefixPath}/user-rights/get-list-module-permission`,
    INSERT_OR_UPDATE_PROFILE_MANAGEMENT: `${prefixPath}/user-rights/insert-or-update-profile`,
    GET_DATA_LIST_OF_USER_PROFILE: `${prefixPath}/user-rights/get-data-list-user-profile`,
    DELETE_PROFILE: `${prefixPath}/user-rights/delete-profile?profileId=`,
    GET_DATA_LIST_PROFILE_NAME_FILTER: `${prefixPath}/user-rights/get-data-list-profile-name-filter`
  },
  login_history: {
    INSERT_LOGOUT_HISTORY_MULTI_LOGIN: `${urlLocation2}/insert-logout-history-multi-login?jSessionID=`,
    INSERT_LOGOUT_HISTORY_SESSION_TIMEOUT: `${urlLocation2}/insert-logout-history-session-timeout?jSessionID=`,
  }
};

export default path;
